# Generated by Django 5.1.2 on 2024-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Book Name')),
                ('book_user', models.CharField(max_length=64, verbose_name='User Name')),
                ('book_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Book Type')),
                ('book_ssin', models.IntegerField(unique=True, verbose_name='Book SSIN')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book plural',
                'db_table': 'book',
                'managed': True,
            },
        ),
    ]
