# Generated by Django 5.1.2 on 2024-11-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_create_date_books_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='delete_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='delete_date'),
        ),
        migrations.AddField(
            model_name='books',
            name='is_delete',
            field=models.IntegerField(blank=True, null=True, verbose_name='is_delete'),
        ),
        migrations.AlterField(
            model_name='books',
            name='create_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='create_date'),
        ),
        migrations.AlterField(
            model_name='books',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update_date'),
        ),
    ]
