# Generated by Django 5.1.2 on 2024-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_delete_date_books_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True, 'verbose_name': 'Book'},
        ),
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='-1', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
