# Generated by Django 5.1.2 on 2024-11-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_create_date_alter_books_delete_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='<function uuid4 at 0x10563dee0>', max_length=50, unique=True, verbose_name='Book Id'),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_delete',
            field=models.IntegerField(default=0, verbose_name='is_delete'),
        ),
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
    ]
