# Generated by Django 5.1.2 on 2024-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_options_alter_books_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='<function uuid4 at 0x1012f5ee0>', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
