# Generated by Django 5.1.2 on 2024-11-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='<function uuid4 at 0x101bb5ee0>', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
