# Generated by Django 5.1.2 on 2024-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='d5b813dbb0b04e79b657464cceeb2b45', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
