# Generated by Django 5.1.2 on 2024-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='f6c57d92b41641e197a83a59296eab1e', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
