# Generated by Django 5.1.2 on 2024-11-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_books_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_content',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='Book Content'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='6380dd13957649cf9107a36b7c9a9307', max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
