# Generated by Django 5.1.2 on 2024-11-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_books_book_content_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Book Id'),
        ),
    ]
