# Generated by Django 5.1.2 on 2024-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_ssin',
            field=models.IntegerField(default='-1', verbose_name='Book SSIN'),
        ),
    ]
